### ISSUE TITLE
Deployment strategy

### ISSUE THREAD

**Issue by alesage** [RBecker262/ChiPyProject#20]
EOM, deployment strategy.  We've discussed at length: need to get both the API and web service running simultaneously using a file share as data store.  I've suggested Elastic Beanstalk as a destination; the existing code depends on running two apps behind a server with different ports.

tl:dr Get this up and running and make us all proud before any more code lands thx.

**Comment by RBecker262** [comment]
Closing issue as this is up and running now and new branches will be submitted for review.
