### ISSUE TITLE
Use datetimes and strftime/strptime in determine_filenames

### ISSUE THREAD

**Issue by alesage** [RBecker262/ChiPyProject#8]
Low priority and to get some experience with the mysteries of datetimes, `updteam:determine_filenames` should take a Python datetime and use `strftime` to generate the path string.  On the intake `strptime` can be used.

Low priority!

**Comment by RBecker262** [comment]
This is addressed in what I submitted yesterday, so once you approve those changes I assume we can close this.

**Comment by RBecker262** [comment]
Closing this now that final change made and submitted.
